import { UseCase } from "../../../../shared/core/UseCase";
import { Result } from "../../../../shared/core/Result";
import { IDecisionOptionRepository } from "../../repos/IDecisionOptionRepository";
import { DecisionOption } from "../../domain/entities/DecisionOption";

export class SeedDecisionUseCase implements UseCase<void, Promise<Result<void>>> {
  constructor(private repo: IDecisionOptionRepository) {}

  async execute(): Promise<Result<void>> {
    const data = [
      
      
      { category: 'movie', title: 'Duro de Matar', primaryFilter: 'acao', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Gladiador', primaryFilter: 'acao', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Missão Impossível: Efeito Fallout', primaryFilter: 'acao', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Capitão América: O Soldado Invernal', primaryFilter: 'acao', secondaryFilter: 'disney' },
      { category: 'movie', title: 'O Protetor', primaryFilter: 'acao', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Click', primaryFilter: 'comedia', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Gente Grande', primaryFilter: 'comedia', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'A Hora do Rush', primaryFilter: 'comedia', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Esqueceram de Mim', primaryFilter: 'comedia', secondaryFilter: 'disney' },
      { category: 'movie', title: 'Legalmente Loira', primaryFilter: 'comedia', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'O Pianista', primaryFilter: 'drama', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Clube da Luta', primaryFilter: 'drama', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'O Resgate do Soldado Ryan', primaryFilter: 'drama', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Coração Valente', primaryFilter: 'drama', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'À Espera de um Milagre', primaryFilter: 'drama', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'O Iluminado', primaryFilter: 'terror', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Atividade Paranormal', primaryFilter: 'terror', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Jogos Mortais', primaryFilter: 'terror', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'A Bruxa', primaryFilter: 'terror', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'O Babadook', primaryFilter: 'terror', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Antes do Amanhecer', primaryFilter: 'romance', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Um Lugar Chamado Notting Hill', primaryFilter: 'romance', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Simplesmente Acontece', primaryFilter: 'romance', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'PS: Eu Te Amo', primaryFilter: 'romance', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Encantada', primaryFilter: 'romance', secondaryFilter: 'disney' },
      { category: 'movie', title: 'Blade Runner 2049', primaryFilter: 'ficcao', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'De Volta para o Futuro', primaryFilter: 'ficcao', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'O Exterminador do Futuro', primaryFilter: 'ficcao', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Avatar', primaryFilter: 'ficcao', secondaryFilter: 'disney' },
      { category: 'movie', title: 'Distrito 9', primaryFilter: 'ficcao', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Mad Max: Estrada da Fúria', primaryFilter: 'acao', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'John Wick', primaryFilter: 'acao', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Pantera Negra', primaryFilter: 'acao', secondaryFilter: 'disney' },
      { category: 'movie', title: 'As Branquelas', primaryFilter: 'comedia', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Todo Mundo em Pânico', primaryFilter: 'comedia', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'O Máskara', primaryFilter: 'comedia', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'À Procura da Felicidade', primaryFilter: 'drama', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Forrest Gump', primaryFilter: 'drama', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Titanic', primaryFilter: 'drama', secondaryFilter: 'disney' },
      { category: 'movie', title: 'Invocação do Mal', primaryFilter: 'terror', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'O Exorcista', primaryFilter: 'terror', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'It: A Coisa', primaryFilter: 'terror', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Como Eu Era Antes de Você', primaryFilter: 'romance', secondaryFilter: 'netflix' },
      { category: 'movie', title: 'Orgulho e Preconceito', primaryFilter: 'romance', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'A Bela e a Fera', primaryFilter: 'romance', secondaryFilter: 'disney' },
      { category: 'movie', title: 'Matrix', primaryFilter: 'ficcao', secondaryFilter: 'hbo' },
      { category: 'movie', title: 'Interestelar', primaryFilter: 'ficcao', secondaryFilter: 'prime video' },
      { category: 'movie', title: 'Star Wars: Uma Nova Esperança', primaryFilter: 'ficcao', secondaryFilter: 'disney' },
      { category: 'food', title: 'Temaki de Salmão', primaryFilter: 'japonesa', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Udon Tradicional', primaryFilter: 'japonesa', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Onigiri', primaryFilter: 'japonesa', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Missoshiro', primaryFilter: 'japonesa', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Spaghetti Carbonara', primaryFilter: 'italiana', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Risoto de Funghi', primaryFilter: 'italiana', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Bruschetta', primaryFilter: 'italiana', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Pizza Margherita', primaryFilter: 'italiana', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Bowl de Frango com Quinoa', primaryFilter: 'fit', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Omelete de Claras', primaryFilter: 'fit', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Iogurte com Granola', primaryFilter: 'fit', secondaryFilter: 'cafe' },
      { category: 'food', title: 'Smoothie Verde', primaryFilter: 'fit', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Frango Xadrez', primaryFilter: 'chinesa', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Rolinho Primavera', primaryFilter: 'chinesa', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Carne com Brócolis', primaryFilter: 'chinesa', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Arroz Chop Suey', primaryFilter: 'chinesa', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Feijoada', primaryFilter: 'brasileira', secondaryFilter: 'almoco' },
      { category: 'food', title: 'Coxinha', primaryFilter: 'brasileira', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Escondidinho de Carne Seca', primaryFilter: 'brasileira', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Tapioca com Queijo', primaryFilter: 'brasileira', secondaryFilter: 'cafe' },
      { category: 'food', title: 'Hambúrguer Artesanal', primaryFilter: 'americana', secondaryFilter: 'jantar' },
      { category: 'food', title: 'Hot Dog', primaryFilter: 'americana', secondaryFilter: 'lanche' },
      { category: 'food', title: 'Panquecas com Maple Syrup', primaryFilter: 'americana', secondaryFilter: 'cafe' },
      { category: 'food', title: 'Costela Barbecue', primaryFilter: 'americana', secondaryFilter: 'almoco' },
      { category: 'drink', title: 'Mojito', primaryFilter: 'drinks', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Caipirinha de Limão', primaryFilter: 'drinks', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Piña Colada', primaryFilter: 'drinks', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Sex on the Beach', primaryFilter: 'drinks', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Negroni', primaryFilter: 'drinks', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Suco de Laranja Natural', primaryFilter: 'suco', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Suco de Abacaxi com Hortelã', primaryFilter: 'suco', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Suco de Melancia', primaryFilter: 'suco', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Suco de Manga', primaryFilter: 'suco', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Suco de Acerola', primaryFilter: 'suco', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Chá de Camomila', primaryFilter: 'cha', secondaryFilter: 'quente' },
      { category: 'drink', title: 'Chá Verde', primaryFilter: 'cha', secondaryFilter: 'quente' },
      { category: 'drink', title: 'Chá Preto com Limão', primaryFilter: 'cha', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Chá de Hortelã', primaryFilter: 'cha', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Chá de Canela', primaryFilter: 'cha', secondaryFilter: 'quente' },
      { category: 'drink', title: 'Whisky com Gelo', primaryFilter: 'destilado', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Vodka Pura', primaryFilter: 'destilado', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Rum Envelhecido', primaryFilter: 'destilado', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Tequila', primaryFilter: 'destilado', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Cachaça Artesanal', primaryFilter: 'destilado', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Guaraná Antarctica', primaryFilter: 'refrigerante', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Fanta Laranja', primaryFilter: 'refrigerante', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Sprite', primaryFilter: 'refrigerante', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Pepsi Twist', primaryFilter: 'refrigerante', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Soda Limão', primaryFilter: 'refrigerante', secondaryFilter: 'refrescante' },
      { category: 'drink', title: 'Milkshake de Chocolate', primaryFilter: 'milkshake', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Milkshake de Baunilha', primaryFilter: 'milkshake', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Milkshake de Ovomaltine', primaryFilter: 'milkshake', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Milkshake de Coco', primaryFilter: 'milkshake', secondaryFilter: 'doce' },
      { category: 'drink', title: 'Milkshake de Banana', primaryFilter: 'milkshake', secondaryFilter: 'doce' },
      { category: 'exercise', title: 'Treino de Peito e Tríceps', primaryFilter: 'musculacao', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Treino de Costas e Bíceps', primaryFilter: 'musculacao', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Treino Funcional com Pesos', primaryFilter: 'musculacao', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Treino de Ombros', primaryFilter: 'musculacao', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Caminhada Leve ao Ar Livre', primaryFilter: 'caminhada', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Caminhada Rápida Urbana', primaryFilter: 'caminhada', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Caminhada Noturna Relaxante', primaryFilter: 'caminhada', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Caminhada em Esteira', primaryFilter: 'caminhada', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Vôlei de Praia', primaryFilter: 'volei', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Treino de Vôlei Recreativo', primaryFilter: 'volei', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Vôlei em Quadra', primaryFilter: 'volei', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Corrida de Rua Moderada', primaryFilter: 'corrida', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Corrida Intervalada', primaryFilter: 'corrida', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Corrida em Esteira', primaryFilter: 'corrida', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Corrida Leve Matinal', primaryFilter: 'corrida', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Treino Aeróbico em Casa', primaryFilter: 'aerobico', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Dança Aeróbica', primaryFilter: 'aerobico', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'HIIT Aeróbico', primaryFilter: 'aerobico', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Step Aeróbico', primaryFilter: 'aerobico', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Futebol Society', primaryFilter: 'futebol', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Futebol de Campo', primaryFilter: 'futebol', secondaryFilter: 'diurno' },
      { category: 'exercise', title: 'Pelada com Amigos', primaryFilter: 'futebol', secondaryFilter: 'noturno' },
      { category: 'exercise', title: 'Treino Técnico de Futebol', primaryFilter: 'futebol', secondaryFilter: 'diurno' },
      { category: 'book', title: 'Harry Potter e a Pedra Filosofal', primaryFilter: 'fantasia', secondaryFilter: 'medio' },
      { category: 'book', title: 'O Nome do Vento', primaryFilter: 'fantasia', secondaryFilter: 'grande' },
      { category: 'book', title: 'As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa', primaryFilter: 'fantasia', secondaryFilter: 'medio' },
      { category: 'book', title: 'Mistborn: O Império Final', primaryFilter: 'fantasia', secondaryFilter: 'grande' },
      { category: 'book', title: 'Coraline', primaryFilter: 'fantasia', secondaryFilter: 'pequena' },
      { category: 'book', title: 'Orgulho e Preconceito', primaryFilter: 'romance', secondaryFilter: 'medio' },
      { category: 'book', title: 'Como Eu Era Antes de Você', primaryFilter: 'romance', secondaryFilter: 'medio' },
      { category: 'book', title: 'A Culpa é das Estrelas', primaryFilter: 'romance', secondaryFilter: 'medio' },
      { category: 'book', title: 'Um Dia', primaryFilter: 'romance', secondaryFilter: 'medio' },
      { category: 'book', title: 'Eleanor & Park', primaryFilter: 'romance', secondaryFilter: 'pequena' },
      { category: 'book', title: 'A Ilha do Tesouro', primaryFilter: 'aventura', secondaryFilter: 'medio' },
      { category: 'book', title: 'As Aventuras de Tom Sawyer', primaryFilter: 'aventura', secondaryFilter: 'medio' },
      { category: 'book', title: 'Viagem ao Centro da Terra', primaryFilter: 'aventura', secondaryFilter: 'medio' },
      { category: 'book', title: 'Robinson Crusoé', primaryFilter: 'aventura', secondaryFilter: 'grande' },
      { category: 'book', title: 'O Velho e o Mar', primaryFilter: 'aventura', secondaryFilter: 'pequena' },
      { category: 'book', title: 'O Iluminado', primaryFilter: 'terror', secondaryFilter: 'grande' },
      { category: 'book', title: 'Drácula', primaryFilter: 'terror', secondaryFilter: 'grande' },
      { category: 'book', title: 'Frankenstein', primaryFilter: 'terror', secondaryFilter: 'medio' },
      { category: 'book', title: 'A Assombração da Casa da Colina', primaryFilter: 'terror', secondaryFilter: 'medio' },
      { category: 'book', title: 'O Chamado de Cthulhu', primaryFilter: 'terror', secondaryFilter: 'pequena' },
      { category: 'book', title: 'O Guia do Mochileiro das Galáxias', primaryFilter: 'humor', secondaryFilter: 'medio' },
      { category: 'book', title: 'Diário de um Banana', primaryFilter: 'humor', secondaryFilter: 'pequena' },
      { category: 'book', title: 'As Aventuras de Bertoldo', primaryFilter: 'humor', secondaryFilter: 'pequena' },
      { category: 'book', title: 'Minha Vida Fora de Série', primaryFilter: 'humor', secondaryFilter: 'medio' },
      { category: 'book', title: 'A Sutil Arte de Ligar o F*da-se', primaryFilter: 'humor', secondaryFilter: 'medio' },
      { category: 'book', title: '1984', primaryFilter: 'ficcao', secondaryFilter: 'medio' },
      { category: 'book', title: 'Admirável Mundo Novo', primaryFilter: 'ficcao', secondaryFilter: 'medio' },
      { category: 'book', title: 'Fahrenheit 451', primaryFilter: 'ficcao', secondaryFilter: 'pequena' },
      { category: 'book', title: 'Duna', primaryFilter: 'ficcao', secondaryFilter: 'grande' },
      { category: 'book', title: 'Neuromancer', primaryFilter: 'ficcao', secondaryFilter: 'medio' },

    ];

    for (const item of data) {
      const option = DecisionOption.create(item as any).getValue();
      await this.repo.save(option);
    }

    return Result.ok();
  }
}